name: event_app
description: Prezenty

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.82+107

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  package_info_plus: ^3.0.1
  fluttertoast: ^8.0.8
  shared_preferences: ^2.0.8
  dio: ^4.0.0
  get: ^4.3.8
  google_sign_in: ^5.1.1
  flutter_colorpicker: ^0.6.0
  screenshot: ^1.2.3
  ##path_provider: ^2.0.5
  permission_handler: ^10.2.0
  image_picker: ^1.0.1
  dotted_border: ^2.0.0+1
  file_picker: ^5.2.2
  audioplayers: ^0.20.1
  photo_view: ^0.13.0
  intl: ^0.17.0
  cached_network_image: ^3.1.0
  syncfusion_flutter_charts: ^19.3.44+1
  camera: ^0.9.4+3
  video_player: ^2.2.5
  flick_video_player: ^0.3.1
  provider: ^5.0.0
  assets_audio_player: ^3.0.5
  flutter_rating_bar: ^4.0.0
  visibility_detector: ^0.2.2
  onesignal_flutter: ^3.2.7
#  add_2_calendar: ^2.1.1
  add_2_calendar: ^2.1.2
#  firebase_dynamic_links: ^2.0.10
  firebase_dynamic_links: ^2.0.3
  #share_plus: ^3.0.2
  otp_text_field: ^1.1.1
  url_launcher: ^6.1.8
  #jitsi_meet: ^4.0.0
  razorpay_flutter: ^1.2.7
  mime_type: ^1.0.0
  sign_in_with_apple: ^3.2.0
  device_info: ^2.0.3
  flutter_image_slideshow: ^0.1.2
  flutter_countdown_timer: ^4.1.0
  flutter_widget_from_html: ^0.8.4
  video_thumbnail: ^0.5.3
  platform: ^3.1.0
  getwidget: ^3.0.1
  web_browser: ^0.5.0
  share_plus: ^4.0.9
  number_paginator: ^0.0.2
  launch_review: ^3.0.1 
  flutter_carousel_widget: ^1.2.3
  flutter_fortune_wheel: ^1.2.0
  animated_text_kit: ^4.2.2
  flutter_gif: ^0.0.4
  qr_flutter: ^4.0.0
  freshchat_sdk: ^0.9.8
  confetti: ^0.7.0
  just_audio: ^0.9.30
  pin_code_fields: ^7.4.0
  carousel_slider: ^4.1.1
  persistent_bottom_nav_bar: ^5.0.2
  badges: ^3.1.1
  http: ^0.13.6



dev_dependencies: 
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/cards/
    - assets/images/
    - assets/images/event_categories/
    - assets/images/event_tile_bg/
    - assets/images/template/
    - assets/images/template/preview/
    - assets/images/you_win.gif

  fonts:
    - family: Akronim
      fonts:
        - asset: assets/fonts/Akronim-Regular.ttf

    - family: BungeeHairline
      fonts:
        - asset: assets/fonts/BungeeHairline-Regular.ttf

    - family: Codystar
      fonts:
        - asset: assets/fonts/Codystar-Regular.ttf

    - family: Cookie
      fonts:
        - asset: assets/fonts/Cookie-Regular.ttf

    - family: DancingScript
      fonts:
        - asset: assets/fonts/DancingScript-VariableFont_wght.ttf

    - family: GreatVibes
      fonts:
        - asset: assets/fonts/GreatVibes-Regular.ttf

    - family: KaushanScript
      fonts:
        - asset: assets/fonts/KaushanScript-Regular.ttf

    - family: MontserratSubrayada
      fonts:
        - asset: assets/fonts/MontserratSubrayada-Regular.ttf

    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf

    - family: Parisienne
      fonts:
        - asset: assets/fonts/Parisienne-Regular.ttf

    - family: Play
      fonts:
        - asset: assets/fonts/Play-Regular.ttf

    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf

    - family: Satisfy
      fonts:
        - asset: assets/fonts/Satisfy-Regular.ttf

    - family: Tangerine
      fonts:
        - asset: assets/fonts/Tangerine-Regular.ttf

    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf

    - family: ZenTokyoZoo
      fonts:
        - asset: assets/fonts/ZenTokyoZoo-Regular.ttf
